######################################################################
##
## Filename: make_A_close_to_B_tb.udo
## Created on: Fri Mar 07 11:38:10 AM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
