######################################################################
##
## Filename: make_A_close_to_B.udo
## Created on: Fri Mar 07 11:37:26 AM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
