######################################################################
##
## Filename: ee201_numlock_sm_tb.udo
## Created on: Fri Feb 07 3:04:27 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
