######################################################################
##
## Filename: divider_tb.udo
## Created on: Mon Feb 17 7:59:19 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
