######################################################################
##
## Filename: ee201_clk_60Hz.udo
## Created on: Fri Feb 21 12:19:22 AM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
