######################################################################
##
## Filename: ee201_clk_60Hz_tb.udo
## Created on: Fri Feb 14 2:23:06 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
