######################################################################
##
## Filename: ee201_pulse_atN_tb.udo
## Created on: Fri Feb 14 2:14:51 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
