######################################################################
##
## Filename: ee201_pulse_atN.udo
## Created on: Mon Feb 17 3:44:19 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
