######################################################################
##
## Filename: ff_reset_tb.udo
## Created on: Mon Feb 17 7:45:39 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
