######################################################################
##
## Filename: ee201_debounce_DPB_SCEN_CCEN_MCEN_tb.udo
## Created on: Fri Mar 07 9:04:44 AM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
