######################################################################
##
## Filename: binary_game.udo
## Created on: Tue Apr 22 8:59:37 PM Pacific Daylight Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
