######################################################################
##
## Filename: binary_game.udo
<<<<<<< HEAD
## Created on: Wed Apr 23 11:24:49 AM China Standard Time 2014
=======
## Created on: Tue Apr 22 8:59:37 PM Pacific Daylight Time 2014
>>>>>>> 2200929ef734f22d18e2ba6586972bd7cebc98fa
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
