######################################################################
##
## Filename: binary_game.udo
## Created on: Wed Apr 23 11:24:49 AM China Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
