######################################################################
##
## Filename: ee201l_number_lock_ee201l_number_lock_sch_tb.udo
## Created on: Fri Jan 31 1:49:33 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
