######################################################################
##
## Filename: ee201l_detour.udo
## Created on: Fri Jan 24 2:40:50 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
