######################################################################
##
## Filename: counter_3bit.udo
## Created on: Fri Apr 04 11:27:35 AM Pacific Daylight Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
